### ISSUE TITLE
Add switch for deleting directory for intermediate files and control database on successful compilation

### ISSUE THREAD

**Issue by apuignav** [aclements/latexrun#32]
While the `--clean-all` switch is provided, it would be a great idea to offer the possibility of removing the `latex.out` (or whatever name) directory after a successful compilation, ie, with no errors.

Currently `--clean-all` also deletes the output file, so there is no way to actually only remove temporary files, AFAIK. I want to open this issue to discuss the topic, I can implement whatever we decide myself an open a PR.

**Comment by FranzSkuffka** [comment]
Not sure if this should be in the scope of this library. Would be useful though but the usecase for a single clean compilation would be a build system or something alike, right? In this case it's trivial to just add a line you makefile or whatever tool you use.

**Comment by aclements** [comment]
I guess I'm not sure what the motivation for this would be. Are you removing `latex.out` because you're about to submit your paper and know that you'll never ever want to build it again? :) It's also quite easy to remove the temporary files: `rm -rf latex.out`. This is one of the reasons I put them in a directory.

**Comment by FranzSkuffka** [comment]
+1 the directory makes this entire thing quite handy already :)

**Comment by apuignav** [comment]
OK! The use case is basically when you finalize a project, have a switch to directly clean things up, but you've convinced me. I'm self-closing :-)
